use crate::kinematics::RobotArm;
use crate::trajectory::TrajectoryPlanner;

/// Exports the recorded trajectory into a standalone, runnable Python script using NumPy.
pub fn export_to_python(robot: &RobotArm, planner: &TrajectoryPlanner) -> String {
    let mut code = String::new();
    code.push_str("#!/usr/bin/env python3\n");
    code.push_str(&format!(
        "# Generated by kine-rs for robot: {}\n",
        robot.name
    ));
    code.push_str("# High-performance robotics kinematics & trajectory planning\n\n");
    code.push_str("import numpy as np\n");
    code.push_str("import matplotlib.pyplot as plt\n\n");

    // Waypoints definition
    code.push_str("# 1. Waypoints (XYZ in meters, Duration in seconds)\n");
    code.push_str("waypoints = [\n");
    let mut cum_time = 0.0;
    for wp in &planner.waypoints {
        cum_time += wp.duration;
        code.push_str(&format!(
            "    {{\"name\": \"{}\", \"pos\": [{:.4}, {:.4}, {:.4}], \"duration\": {:.2}, \"time\": {:.2}}},\n",
            wp.name, wp.position.x, wp.position.y, wp.position.z, wp.duration, cum_time
        ));
    }
    code.push_str("]\n\n");

    // Sampled Path
    let samples = planner.sample_path(50);
    code.push_str("# 2. Interpolated Minimum-Jerk Cartesian Trajectory\n");
    code.push_str("trajectory_points = np.array([\n");
    for pt in &samples {
        code.push_str(&format!("    [{:.4}, {:.4}, {:.4}],\n", pt.x, pt.y, pt.z));
    }
    code.push_str("])\n\n");

    // Visualization snippet
    code.push_str("def plot_trajectory():\n");
    code.push_str("    fig = plt.figure(figsize=(10, 8))\n");
    code.push_str("    ax = fig.add_subplot(111, projection='3d')\n");
    code.push_str("    ax.plot(trajectory_points[:, 0], trajectory_points[:, 1], trajectory_points[:, 2], 'b-', label='Planned Path', linewidth=2)\n");
    code.push_str("    if len(waypoints) > 0:\n");
    code.push_str("        wp_arr = np.array([w['pos'] for w in waypoints])\n");
    code.push_str("        ax.scatter(wp_arr[:, 0], wp_arr[:, 1], wp_arr[:, 2], color='red', s=60, label='Waypoints')\n");
    code.push_str("    ax.set_xlabel('X [m]')\n");
    code.push_str("    ax.set_ylabel('Y [m]')\n");
    code.push_str("    ax.set_zlabel('Z [m]')\n");
    code.push_str(&format!(
        "    ax.set_title('Robot Trajectory: {}')\n",
        robot.name
    ));
    code.push_str("    ax.legend()\n");
    code.push_str("    plt.tight_layout()\n");
    code.push_str("    plt.show()\n\n");

    code.push_str("if __name__ == '__main__':\n");
    code.push_str("    print(f'Total waypoints: {len(waypoints)}')\n");
    code.push_str("    print(f'Sampled trajectory length: {len(trajectory_points)}')\n");
    code.push_str("    plot_trajectory()\n");

    code
}

/// Exports the trajectory into a ROS 2 `trajectory_msgs/JointTrajectory` YAML payload.
pub fn export_to_ros2(robot: &RobotArm, planner: &TrajectoryPlanner) -> String {
    let mut yaml = String::new();
    yaml.push_str("# ROS 2 trajectory_msgs/msg/JointTrajectory\n");
    yaml.push_str("header:\n");
    yaml.push_str("  stamp:\n");
    yaml.push_str("    sec: 0\n");
    yaml.push_str("    nanosec: 0\n");
    yaml.push_str("  frame_id: \"base_link\"\n");
    yaml.push_str("joint_names:\n");
    for joint in &robot.joints {
        yaml.push_str(&format!("  - \"{}\"\n", joint.name));
    }

    yaml.push_str("points:\n");
    let current_q = robot.get_actuated_joint_positions();

    let mut cum_time = 0.0;
    for (idx, wp) in planner.waypoints.iter().enumerate() {
        cum_time += wp.duration;
        yaml.push_str(&format!("  - # Waypoint {}: {}\n", idx + 1, wp.name));
        yaml.push_str("    positions: [");
        for (j, q) in current_q.iter().enumerate() {
            if j > 0 {
                yaml.push_str(", ");
            }
            yaml.push_str(&format!("{:.4}", q));
        }
        yaml.push_str("]\n");
        yaml.push_str("    velocities: [");
        for j in 0..current_q.len() {
            if j > 0 {
                yaml.push_str(", ");
            }
            yaml.push_str("0.0");
        }
        yaml.push_str("]\n");
        let sec = cum_time.floor() as i64;
        let nanosec = ((cum_time - sec as f64) * 1e9) as u32;
        yaml.push_str(&format!("    time_from_start:\n      sec: {}\n      nanosec: {}\n", sec, nanosec));
    }

    yaml
}

/// Exports the trajectory into standard CNC G-code and CSV time-series formats.
pub fn export_to_gcode_csv(robot: &RobotArm, planner: &TrajectoryPlanner) -> String {
    let mut out = String::new();
    out.push_str(&format!("; --- G-CODE PROGRAM FOR ROBOT: {} ---\n", robot.name));
    out.push_str("; Metric units, absolute positioning, linear feed 1200 mm/min\n");
    out.push_str("G21 ; Millimeters\n");
    out.push_str("G90 ; Absolute coordinates\n");
    out.push_str("F1200.0 ; Feedrate\n\n");

    for (idx, wp) in planner.waypoints.iter().enumerate() {
        let x_mm = wp.position.x * 1000.0;
        let y_mm = wp.position.y * 1000.0;
        let z_mm = wp.position.z * 1000.0;
        out.push_str(&format!(
            "G01 X{:.3} Y{:.3} Z{:.3} ; Waypoint {}\n",
            x_mm, y_mm, z_mm, idx + 1
        ));
    }
    out.push_str("M30 ; End of program\n\n");

    out.push_str("# --- CSV TRAJECTORY TIME-SERIES ---\n");
    out.push_str("time_s,x_m,y_m,z_m\n");
    let samples = planner.sample_path(40);
    let total_dur = planner.total_duration.max(0.1);
    for (i, pt) in samples.iter().enumerate() {
        let t = (i as f64 / samples.len().max(1) as f64) * total_dur;
        out.push_str(&format!("{:.3},{:.4},{:.4},{:.4}\n", t, pt.x, pt.y, pt.z));
    }

    out
}
