use serde::{Deserialize, Serialize};

use crate::kinematics::RobotArm;
use crate::trajectory::{TrajectoryPlanner, TrajectoryRecording, Waypoint};

/// Structured container for full trajectory session import / export.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrajectorySessionExport {
    pub format_version: String,
    pub robot_name: String,
    pub robot_dof: usize,
    pub waypoints: Vec<Waypoint>,
    pub recording: Option<TrajectoryRecording>,
}

/// Exports the recorded trajectory into a standalone, runnable Python script using NumPy and Matplotlib.
pub fn export_to_python(robot: &RobotArm, planner: &TrajectoryPlanner) -> String {
    let mut code = String::new();
    code.push_str("#!/usr/bin/env python3\n");
    code.push_str(&format!(
        "# Generated by Robo-arm (kine-rs) for robot: {}\n",
        robot.name
    ));
    code.push_str("# High-performance robotics kinematics & trajectory planning\n\n");
    code.push_str("import numpy as np\n");
    code.push_str("import matplotlib.pyplot as plt\n\n");

    // Waypoints definition
    code.push_str("# 1. Waypoints (XYZ in meters, Duration in seconds)\n");
    code.push_str("waypoints = [\n");
    let mut cum_time = 0.0;
    for wp in &planner.waypoints {
        cum_time += wp.duration;
        code.push_str(&format!(
            "    {{\"name\": \"{}\", \"pos\": [{:.4}, {:.4}, {:.4}], \"duration\": {:.2}, \"time\": {:.2}}},\n",
            wp.name, wp.position.x, wp.position.y, wp.position.z, wp.duration, cum_time
        ));
    }
    code.push_str("]\n\n");

    // Sampled Path
    let samples = planner.sample_path(50);
    code.push_str("# 2. Interpolated Minimum-Jerk Cartesian Trajectory\n");
    code.push_str("trajectory_points = np.array([\n");
    for pt in &samples {
        code.push_str(&format!("    [{:.4}, {:.4}, {:.4}],\n", pt.x, pt.y, pt.z));
    }
    code.push_str("])\n\n");

    // Visualization snippet
    code.push_str("def plot_trajectory():\n");
    code.push_str("    fig = plt.figure(figsize=(10, 8))\n");
    code.push_str("    ax = fig.add_subplot(111, projection='3d')\n");
    code.push_str("    ax.plot(trajectory_points[:, 0], trajectory_points[:, 1], trajectory_points[:, 2], 'b-', label='Planned Path', linewidth=2)\n");
    if !planner.waypoints.is_empty() {
        code.push_str("    wp_arr = np.array([w['pos'] for w in waypoints])\n");
        code.push_str("    ax.scatter(wp_arr[:, 0], wp_arr[:, 1], wp_arr[:, 2], color='red', s=60, label='Waypoints')\n");
    }
    code.push_str("    ax.set_xlabel('X [m]')\n");
    code.push_str("    ax.set_ylabel('Y [m]')\n");
    code.push_str("    ax.set_zlabel('Z [m]')\n");
    code.push_str(&format!(
        "    ax.set_title('Robot Trajectory: {}')\n",
        robot.name
    ));
    code.push_str("    ax.legend()\n");
    code.push_str("    plt.tight_layout()\n");
    code.push_str("    plt.show()\n\n");

    code.push_str("if __name__ == '__main__':\n");
    code.push_str("    print(f'Total waypoints: {len(waypoints)}')\n");
    code.push_str("    print(f'Sampled trajectory length: {len(trajectory_points)}')\n");
    code.push_str("    plot_trajectory()\n");

    code
}

/// Exports the trajectory into a ROS 2 `trajectory_msgs/JointTrajectory` YAML payload.
pub fn export_to_ros2(robot: &RobotArm, planner: &TrajectoryPlanner) -> String {
    let mut yaml = String::new();
    yaml.push_str("# ROS 2 trajectory_msgs/msg/JointTrajectory\n");
    yaml.push_str("header:\n");
    yaml.push_str("  stamp:\n");
    yaml.push_str("    sec: 0\n");
    yaml.push_str("    nanosec: 0\n");
    yaml.push_str("  frame_id: \"base_link\"\n");
    yaml.push_str("joint_names:\n");
    for joint in &robot.joints {
        yaml.push_str(&format!("  - \"{}\"\n", joint.name));
    }

    yaml.push_str("points:\n");
    let current_q = robot.get_actuated_joint_positions();

    let mut cum_time = 0.0;
    for (idx, wp) in planner.waypoints.iter().enumerate() {
        cum_time += wp.duration;
        yaml.push_str(&format!("  - # Waypoint {}: {}\n", idx + 1, wp.name));
        yaml.push_str("    positions: [");
        for (j, q) in current_q.iter().enumerate() {
            if j > 0 {
                yaml.push_str(", ");
            }
            yaml.push_str(&format!("{:.4}", q));
        }
        yaml.push_str("]\n");
        yaml.push_str("    velocities: [");
        for j in 0..current_q.len() {
            if j > 0 {
                yaml.push_str(", ");
            }
            yaml.push_str("0.0");
        }
        yaml.push_str("]\n");
        let sec = cum_time.floor() as i64;
        let nanosec = ((cum_time - sec as f64) * 1e9) as u32;
        yaml.push_str(&format!(
            "    time_from_start:\n      sec: {}\n      nanosec: {}\n",
            sec, nanosec
        ));
    }

    yaml
}

/// Exports the trajectory into standard CNC G-code and CSV time-series formats.
pub fn export_to_gcode_csv(robot: &RobotArm, planner: &TrajectoryPlanner) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "; --- G-CODE PROGRAM FOR ROBOT: {} ---\n",
        robot.name
    ));
    out.push_str("; Metric units, absolute positioning, linear feed 1200 mm/min\n");
    out.push_str("G21 ; Millimeters\n");
    out.push_str("G90 ; Absolute coordinates\n");
    out.push_str("F1200.0 ; Feedrate\n\n");

    for (idx, wp) in planner.waypoints.iter().enumerate() {
        let x_mm = wp.position.x * 1000.0;
        let y_mm = wp.position.y * 1000.0;
        let z_mm = wp.position.z * 1000.0;
        out.push_str(&format!(
            "G01 X{:.3} Y{:.3} Z{:.3} ; Waypoint {}\n",
            x_mm,
            y_mm,
            z_mm,
            idx + 1
        ));
    }
    out.push_str("M30 ; End of program\n\n");

    out.push_str("# --- CSV TRAJECTORY TIME-SERIES ---\n");
    out.push_str("time_s,x_m,y_m,z_m\n");
    let samples = planner.sample_path(40);
    let total_dur = planner.total_duration.max(0.1);
    for (i, pt) in samples.iter().enumerate() {
        let t = (i as f64 / samples.len().max(1) as f64) * total_dur;
        out.push_str(&format!("{:.3},{:.4},{:.4},{:.4}\n", t, pt.x, pt.y, pt.z));
    }

    out
}

/// Exports the entire trajectory and optional recording into formatted JSON.
pub fn export_to_json(
    robot: &RobotArm,
    planner: &TrajectoryPlanner,
    recording: Option<&TrajectoryRecording>,
) -> String {
    let payload = TrajectorySessionExport {
        format_version: "kine-rs-trajectory-v1.0".to_string(),
        robot_name: robot.name.clone(),
        robot_dof: robot.dof(),
        waypoints: planner.waypoints.clone(),
        recording: recording.cloned(),
    };

    serde_json::to_string_pretty(&payload).unwrap_or_else(|_| "{}".to_string())
}

/// Imports waypoints and optional recording from JSON string.
pub fn import_from_json(
    json_str: &str,
) -> Result<(Vec<Waypoint>, Option<TrajectoryRecording>), String> {
    let payload: TrajectorySessionExport =
        serde_json::from_str(json_str).map_err(|e| format!("JSON deserialization error: {}", e))?;

    Ok((payload.waypoints, payload.recording))
}

/// Exports recorded live frames into standard CSV time-series format.
pub fn export_recorded_to_csv(recording: &TrajectoryRecording) -> String {
    let mut csv = String::new();
    csv.push_str("time_s,x_m,y_m,z_m,roll_deg,pitch_deg,yaw_deg,gripper\n");

    for f in &recording.frames {
        csv.push_str(&format!(
            "{:.3},{:.4},{:.4},{:.4},{:.2},{:.2},{:.2},{:.3}\n",
            f.time,
            f.ee_position.x,
            f.ee_position.y,
            f.ee_position.z,
            f.ee_rpy_deg[0],
            f.ee_rpy_deg[1],
            f.ee_rpy_deg[2],
            f.gripper_value
        ));
    }

    csv
}

/// Exports trajectory into an Arduino / C++ microcontroller sketch.
pub fn export_to_arduino_cpp(
    robot: &RobotArm,
    planner: &TrajectoryPlanner,
    recording: Option<&TrajectoryRecording>,
) -> String {
    let mut cpp = String::new();
    cpp.push_str("// ======================================================================\n");
    cpp.push_str(&format!(
        "// Arduino / ESP32 Robot Arm Motion Driver - {}\n",
        robot.name
    ));
    cpp.push_str("// Generated by Robo-arm (kine-rs) Robotics Engine\n");
    cpp.push_str("// ======================================================================\n\n");
    cpp.push_str("#include <Servo.h>\n\n");

    let num_servos = robot.dof().clamp(1, 8);
    cpp.push_str(&format!("const int NUM_SERVOS = {};\n", num_servos));
    cpp.push_str("Servo servos[NUM_SERVOS];\n");
    cpp.push_str("const int servoPins[NUM_SERVOS] = {3, 5, 6, 9, 10, 11}; // PWM Pins\n\n");

    // Keyframe positions (either from recording frames or waypoints)
    let current_q = robot.get_actuated_joint_positions();
    let num_points = if let Some(rec) = recording {
        if !rec.is_empty() {
            rec.frames.len().min(30)
        } else {
            planner.waypoints.len().max(1)
        }
    } else {
        planner.waypoints.len().max(1)
    };

    cpp.push_str(&format!("const int NUM_KEYFRAMES = {};\n", num_points));
    cpp.push_str("// Joint Target Angles (Degrees, 0 to 180)\n");
    cpp.push_str("const int jointKeyframes[NUM_KEYFRAMES][NUM_SERVOS] = {\n");

    if let Some(rec) = recording {
        if !rec.is_empty() {
            let step = (rec.frames.len() as f64 / num_points as f64).max(1.0);
            for k in 0..num_points {
                let idx = ((k as f64 * step).round() as usize).min(rec.frames.len() - 1);
                let f = &rec.frames[idx];
                cpp.push_str("    {");
                for j in 0..num_servos {
                    let rad = if j < f.joint_positions.len() {
                        f.joint_positions[j]
                    } else {
                        0.0
                    };
                    let deg = ((rad.to_degrees() + 90.0).clamp(0.0, 180.0)).round() as i32;
                    if j > 0 {
                        cpp.push_str(", ");
                    }
                    cpp.push_str(&format!("{}", deg));
                }
                cpp.push_str("},\n");
            }
        } else {
            // Default current pose
            cpp.push_str("    {");
            for j in 0..num_servos {
                let rad = if j < current_q.len() {
                    current_q[j]
                } else {
                    0.0
                };
                let deg = ((rad.to_degrees() + 90.0).clamp(0.0, 180.0)).round() as i32;
                if j > 0 {
                    cpp.push_str(", ");
                }
                cpp.push_str(&format!("{}", deg));
            }
            cpp.push_str("}\n");
        }
    } else {
        cpp.push_str("    {");
        for j in 0..num_servos {
            let rad = if j < current_q.len() {
                current_q[j]
            } else {
                0.0
            };
            let deg = ((rad.to_degrees() + 90.0).clamp(0.0, 180.0)).round() as i32;
            if j > 0 {
                cpp.push_str(", ");
            }
            cpp.push_str(&format!("{}", deg));
        }
        cpp.push_str("}\n");
    }

    cpp.push_str("};\n\n");

    cpp.push_str("void setup() {\n");
    cpp.push_str("    Serial.begin(115200);\n");
    cpp.push_str("    Serial.println(\"Initializing Robo-Arm Servos...\");\n");
    cpp.push_str("    for (int i = 0; i < NUM_SERVOS; i++) {\n");
    cpp.push_str("        servos[i].attach(servoPins[i]);\n");
    cpp.push_str("        servos[i].write(90); // Default neutral pose\n");
    cpp.push_str("    }\n");
    cpp.push_str("    delay(1000);\n");
    cpp.push_str("}\n\n");

    cpp.push_str("void loop() {\n");
    cpp.push_str("    for (int k = 0; k < NUM_KEYFRAMES; k++) {\n");
    cpp.push_str("        Serial.print(\"Moving to Keyframe \");\n");
    cpp.push_str("        Serial.println(k + 1);\n");
    cpp.push_str("        for (int i = 0; i < NUM_SERVOS; i++) {\n");
    cpp.push_str("            servos[i].write(jointKeyframes[k][i]);\n");
    cpp.push_str("        }\n");
    cpp.push_str("        delay(1200); // Dwell time between waypoints\n");
    cpp.push_str("    }\n");
    cpp.push_str("    delay(2000); // Loop wait\n");
    cpp.push_str("}\n");

    cpp
}

/// Exports trajectory into a standalone MATLAB / Simulink robotics script.
pub fn export_to_matlab(
    robot: &RobotArm,
    planner: &TrajectoryPlanner,
    recording: Option<&TrajectoryRecording>,
) -> String {
    let mut m = String::new();
    m.push_str("%% ======================================================================\n");
    m.push_str(&format!(
        "%% MATLAB Trajectory Simulation Script - {}\n",
        robot.name
    ));
    m.push_str("%% Generated by Robo-arm (kine-rs) pure Rust robotics engine\n");
    m.push_str("%% ======================================================================\n\n");
    m.push_str("clear; clc; close all;\n\n");

    m.push_str("%% 1. Planned Cartesian Trajectory (X, Y, Z in meters)\n");
    m.push_str("cartesian_traj = [\n");

    let samples = if let Some(rec) = recording {
        if !rec.is_empty() {
            rec.frames.iter().map(|f| f.ee_position).collect::<Vec<_>>()
        } else {
            planner.sample_path(50)
        }
    } else {
        planner.sample_path(50)
    };

    for pt in &samples {
        m.push_str(&format!("    {:.4}, {:.4}, {:.4};\n", pt.x, pt.y, pt.z));
    }
    m.push_str("];\n\n");

    m.push_str("%% 2. Waypoint Targets\n");
    m.push_str("waypoints = [\n");
    for wp in &planner.waypoints {
        m.push_str(&format!(
            "    {:.4}, {:.4}, {:.4};\n",
            wp.position.x, wp.position.y, wp.position.z
        ));
    }
    m.push_str("];\n\n");

    m.push_str("%% 3. Plotting in 3D\n");
    m.push_str("figure('Name', 'Robo-arm Trajectory', 'Color', 'w');\n");
    m.push_str("plot3(cartesian_traj(:, 1), cartesian_traj(:, 2), cartesian_traj(:, 3), 'b-', 'LineWidth', 2.2);\n");
    m.push_str("hold on; grid on; axis equal;\n");
    if !planner.waypoints.is_empty() {
        m.push_str("plot3(waypoints(:, 1), waypoints(:, 2), waypoints(:, 3), 'ro', 'MarkerFaceColor', 'r', 'MarkerSize', 8);\n");
    }
    m.push_str("xlabel('X [m]'); ylabel('Y [m]'); zlabel('Z [m]');\n");
    m.push_str(&format!(
        "title('3D Trajectory Profile: {}');\n",
        robot.name
    ));
    m.push_str("legend({'Trajectory Path', 'Waypoints'}, 'Location', 'best');\n");
    m.push_str("view(45, 30);\n");

    m
}
